import React from 'react';
import InputGroup from './group/input-group';
import { AUTO_SUFFIX } from '../../validation';

let group = {
  invalid: '',
  inputId: '',
  required: '',
  disable: '',
};

let label = {
  id: '',
  disabled: '',
  children: '',
  htmlFor: '',
};

let description = {
  id: '',
  children: '',
};

let error = {
  id: '',
  children: '',
};

let input = {
  invalid: '',
  required: '',
  disabled: '',
  labelid: '',
  id: '',
  placeholder: '',
  name: '',
  type: '',
  description: '',
  minlength: '',
  maxlength: '',
  datatype: '',
  autocomplete: '',
  spellcheck: '',
};

// Can specify label, description, input, error using object
// or those can be autogenerated based on other props
const AutoInput = ({
  id,
  required = false,
  group = null,
  label = null,
  description,
  error = null,
  input = null,
  labelText = '',
}) => {
  const inputId = input?.id ?? id;
  const computedLabelId = `${inputId}${AUTO_SUFFIX.LABEL}`;
  const computedErrorMsgId = `${inputId}${AUTO_SUFFIX.ERROR_MSG}`;

  const buildLabelId = () => {
    return label?.id ?? computedLabelId;
  };

  const buildLabelFor = () => {
    return label?.for ?? inputId;
  };

  const buildLabelText = () => {
    return label?.text ?? labelText;
  };

  const buildErrorMessageId = () => {
    return error?.id ?? computedErrorMsgId;
  };

  const buildGroupId = () => {
    return group?.inputId ?? inputId;
  };

  const buildInputRequired = () => {
    return input?.required ?? required;
  };

  const buildInputName = () => {
    return input?.name ?? inputId;
  };

  const groupId = buildGroupId();
  const labelId = buildLabelId();
  const labelFor = buildLabelFor();
  const labelTextValue = buildLabelText();
  const errorMessageId = buildErrorMessageId();
  const inputRequired = buildInputRequired();
  const inputName = buildInputName();
  return (
    <InputGroup required={inputRequired} inputId={groupId}>
      <InputGroup.Label id={labelId} htmlFor={labelFor}>
        {labelTextValue}
      </InputGroup.Label>
      {description && (
        <InputGroup.Description>
          {description.text}
          {description.children}
        </InputGroup.Description>
      )}
      <InputGroup.Error id={errorMessageId} />
      <InputGroup.Input
        required={inputRequired}
        labelId={labelId}
        errorMessageId={errorMessageId}
        id={inputId}
        name={inputName}
      />
    </InputGroup>
  );
};

export default AutoInput;
